# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactManagement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactManagement
pod 'AFNetworking', '~> 3.0'
pod 'MagicalRecord'
pod 'SDWebImage', '~>3.8'

  target 'ContactManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactManagementUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
